version: '3.7'

services:
  cat-app:
    image: mikesir87/cats
    networks:
      - inbound
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.http.routers.cats.rule=Host(`cats.localhost`)"
        - "traefik.http.routers.cats.service=cats"
        - "traefik.http.services.cats.loadbalancer.server.port=5000"
        - "traefik.docker.network=inbound"
networks:
  inbound:
   external: true