{
 "title": "Traefik2",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service)" },
   { "name": "entrypoint", "query": "label_values(entrypoint)" }
  ]
 },
 "panels": [
  {
   "title": "$service stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "traefik_service_requests_total{service=\"$service\"}"
      }
     ]
    },
    {
     "title": "$service return code",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "traefik_service_requests_total{service=\"$service\"}",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "$service response time",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"$service\"}) / sum(traefik_service_requests_total{service=\"$service\"}) * 1000"
      }
     ]
    },
    {
     "title": "Total requests over 5min $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{service=\"$service\"}[5m]))",
       "legendFormat": "Total requests $service"
      }
     ]
    }
   ]
  },
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=\"200\"}[5m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Others status code over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code!=\"200\"}[5m])",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint =~ \"$entrypoint\"}[5m])) by (entrypoint) ",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  }
 ]
}